import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/redux/Providers";


export const metadata: Metadata = {
  title: "Chat app",
  description: "Generated by priyanshoe",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body>
        <Providers>
          {
            children
          }
        </Providers>
      </body>
    </html>
  );
}
